### ISSUE TITLE
We must be able to accept and reject a request from the future balance supplier for a move in on a consumption metering point

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-market-roles#463]
As a market actor 
I want to be able to perform a move in for a customer and receive a response
So that I know if the move in has been completed

**Acceptance criteria**

- [x] We reject message if GSRN and CPR/CVR are not valid
- [x] The customer has been registered on the accounting point
- [x] The balance supplier has been registered on the accounting point
- [ ] Solution is deployed to test

**Tasks**

- [x] Extend Processing Function with Command Handler for Move In process #556

- [ ] Create Move In Result Handler #559

- [x] Input Validation for Move In #558

**Comment by Christian-Meyer** [comment]
Type	GLN	Name
Energy supplier	8200000007401	DDQ-1
Energy supplier	8200000007418	DDQ-2
Energy supplier	8200000007425	DDQ-3
Energy supplier	8200000007432	DDQ-4
Grid access provider	8200000007449	DDM-1
Grid access provider	8200000007456	DDM-2
Grid access provider	8200000007463	DDM-3
Grid access provider	8200000007470	DDM-4
Grid access provider	8200000007487	DDM-5
Grid access provider	8200000007494	DDM-6
Grid access provider	8200000007500	DDM-7
Grid access provider	8200000007517	DDM-8
Grid access provider	8200000007524	DDM-9
Grid access provider	8200000007531	DDM-10

**Comment by Christian-Meyer** [comment]
Solution is not deployed to test, as we do not have a working test enviroment in market role.
