### ISSUE TITLE
We must be able to inform other domains about a move in on a consumption metering point

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-market-roles#464]
As market role domain 
We want to be able to inform other domain about a move in
So that other domains can use this information for business processes

**Acceptance criteria**

- [ ] We can inform other domains about a move in

**Tasks**

- [ ] Raise Integration Event on Move In #560
- [ ] Dispatch Integration Event on Move In #561

**Comment by erduna** [comment]
Same as #561
