### ISSUE TITLE
BRS-009 - Perform Move-in

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-market-roles#666]
**Description**

This feature builds further upon the simple move-in process that has already been developed. In this feature we add additional functionality to the move-in process. We add: Request update customer master data, request cancel move-in process and send information to various market actors.

**Acceptance criteria**

- [ ] A future balance supplier can request a move-in using all three move-in reasons
- [ ] We can accept/reject the request from the future balance supplier
- [ ] A future balance supplier can receive a response about their request
- [ ] We can inform future and current balance supplier about the move-in
- [ ] A future balance supplier can request update customer master data
- [ ] We can accept/reject a request update customer master data
- [ ] We can inform a future balance supplier about their request update customer master data
- [ ] A future balance supplier can cancel their request for move-in
- [ ] We can accept/reject a request for cancel move-in
- [ ] We can inform a future balance supplier about their request cancel move-in
- [ ] We can inform grid company about move-in
- [ ] We can inform current balance supplier about stop      

The team has assessed that it will take 2 developers 3 sprints to complete this feature.

**Comment by ENDK-CCO** [comment]
CCO: test af rettigheder
