### ISSUE TITLE
Actor management for grid operators

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-market-roles#674]
[https://app.zenhub.com/files/345461101/aab5df53-8577-44a8-8d8d-6df5619dbcf6/download](https://app.zenhub.com/files/345461101/aab5df53-8577-44a8-8d8d-6df5619dbcf6/download)[https://app.zenhub.com/files/345461101/57f3c78b-1127-49b9-a0e2-289d4ae863d1/download](https://app.zenhub.com/files/345461101/57f3c78b-1127-49b9-a0e2-289d4ae863d1/download)[https://app.zenhub.com/files/345461101/0aa7bc5c-5e64-421a-bcc2-063f39de8efd/download](https://app.zenhub.com/files/345461101/0aa7bc5c-5e64-421a-bcc2-063f39de8efd/download)[https://app.zenhub.com/files/345461101/403367cf-f273-4ff5-952e-f807d71a259e/download](https://app.zenhub.com/files/345461101/403367cf-f273-4ff5-952e-f807d71a259e/download)**Description**

In order for us to know what actors have which roles, and decide what they are allowed to do. We need to register actors and their roles within the system. 

Example.
_A grid company has a role that allows them to create new metering points and update metering point master data. 
A balance supplier cannot create new metering points. But can initiate other processes._ 

The creation of actors is not done via a BRS but is done via a GUI. It is only DH that can create new actors. The verification of new actors is a process that starts prior to creation and is handled outside of DH.

The scope of this feature is not to create actors via a GUI. It is to have a place to store actors and the handling of which actors can do what. And to determine which actors can receive certain information, and to make sure they only receive information they are allowed to.   

**Acceptance criteria**

- [ ] We have a place to store information about actors.
- [ ] Actors can be given roles which allows them to perform certain actions within the system. 
- [ ] Only permitted actors can perform certain actions.
- [ ] We can ensure that actors only receive information they are permitted to receive.

**Comment by Tm1807** [comment]
[https://app.zenhub.com/files/345461101/e8f5c7fe-b500-421c-b0e9-425f3c73e0b8/download](https://app.zenhub.com/files/345461101/e8f5c7fe-b500-421c-b0e9-425f3c73e0b8/download)[https://app.zenhub.com/files/345461101/525c97e7-529f-43c1-a241-333d73aa002a/download](https://app.zenhub.com/files/345461101/525c97e7-529f-43c1-a241-333d73aa002a/download)

**Comment by Tm1807** [comment]
Added two files
