### ISSUE TITLE
Expose interface/contract for invoking process for charge links attachment as part of BRS-004

### ISSUE THREAD

**Issue by kft** [Energinet-DataHub/geh-market-roles#712]
**Benefit hypothesis**

**Description**

**Acceptance criteria**

- [ ] 

**Tasks**
- [ ] 
 
**DoD**

- [ ] All tasks have been completed
- [ ] All acceptance criteria have been completed
- [ ] Unit test performed
- [ ] Integration test performed
- [ ] Tested
- [ ] Solution is deployed to test environment

**Comment by Christian-Meyer** [comment]
@Korgath After the meeting with Volt is it possible to update this story?

**Comment by Korgath** [comment]
@Christian-Meyer I'll update this after the integration event meeting hosted by Søren this afternoon

**Comment by Christian-Meyer** [comment]
@Korgath Cool, Thx.

**Comment by Christian-Meyer** [comment]
![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/60bf67953ffc7e5c3e70b6a8/e146f1ee-0e6e-48c1-8c89-f08532d4a906)

**Comment by Christian-Meyer** [comment]
This will be done in #328. This story is closed.
