### ISSUE TITLE
Receive move-in request

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-market-roles#773]
**Benefit hypothesis**
As a energy supplier
We want to get our message XML validated
So that we know if the format is correct

**Description**
This story makes it possible for us to validate the incoming message and check if the XML schema is valid

**Acceptance criteria**
- [x] Receive request
- [x] Be able to validate XML schema
- [x] Be able to validate message ID 
- [x] Be able to extract activity record
- [x] Be able to validate transaction ID
- [x] Forward message to transaction handling

**Tasks**

- [x] Implementere AZ function med HTTP trigger (CBS)
- Delegate til MessageReceiver 
- Impl. Response/Request logging-ting-nuget-shit 
- Impl. TerraForm (TF) (IaC) 
- Inkl. API management config 
- Authentication 

- [x] Impl. MarketActivityRecordForwarder 
- Dispatches til Servicebus queue   XIKMA 
- Impl. SB queue inkl. TF 

- [x] Implementerer message id store DPH 
- Replace MessageIdsStub med implementering (evt. I SQL database) 

- [x] Implementerer transaction id store DPH 
- Replace TransactionIdsStub med implementering (evt. I SQL database) 

- [x] Impl. HTTP response factory (KFT) 
- Tager Result fra MessageReceiver 
- Skal kunne unittests uafhængig af host 
- Structure findes på energinet.dk 

- [x] Refactor MarketActivityRecord (KFT) 

- [x] Impl. XML schema provider 

- [x] Validation of receiver and receiver role 

- [x] Validation (authorization) of sender role 

- [x] Refactor TransactionQueueDispatcher 

- [x] Skift pegepind på APIM
