### ISSUE TITLE
Notify current energy supplier when customer and energy supplier is changed on the metering point

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-market-roles#779]
**Benefit hypothesis**
As a energy supplier
We want the energy supplier to be changed on the metering point and the customer to be changed as well as informing the current energy supplier about the stop of power to the MP
So that the new energy supplier and customer is registered.

**Description**
This story finalizes the move-in by changing the customer and the energy supplier on the metering point, and generates a message to the current energy supplier informing them about them loosing the metering point

**Acceptance criteria**
- [x] Change the customer on the metering point
- [x] Change the energy supplier on the metering point
- [x] Generate a message (Generic notification business reason code E01) to the current energy supplier informing them about stop of delivery to the metering point

**Tasks**
- [x] Revisit current logic to see how much can be reused
- [x] Before starting this user story developers must hold a TDD session as mob programming
- [x] Publish event to other domains

**Comment by Christian-Meyer** [comment]
Awaiting confirmation from business. They are checking if message is correct.

**Comment by Christian-Meyer** [comment]
There is a minor issue with cim:type that we are fixing in #1113

**Comment by Christian-Meyer** [comment]
Comment. Discuss original transaction ID with CCO and KFT.
